name: inventario
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  curved_navigation_bar: ^1.0.6
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_calendar_week: ^3.0.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: 2.4.1
  flutter_neat_and_clean_calendar: ^0.4.15
  flutter_speed_dial: ^7.0.0
  fluttertoast: ^8.2.6
  footer: ^0.0.4
  gap: ^3.0.1
  go_router: ^14.2.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpeg"
  min_sdk_android: 21
  adaptive-icon_background: "#FFFFFF"
  adaptive_icon_foreground: "#ffffff"

flutter_native_splash:
  color: "#223ef1"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icon/
